### ISSUE TITLE
Ruby 3 support

### ISSUE THREAD

**Issue by zedtux** [zedtux/database_cleaner-nobrainer#1]
The gem breaks with Ruby 3 :

```
           +cucumber | wrong number of arguments (given 1, expected 0) (ArgumentError)
           +cucumber | /usr/local/bundle/gems/database_cleaner-nobrainer-1.0.0/lib/database_cleaner/nobrainer/deletion.rb:8:in `initialize'
           +cucumber | /usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaner.rb:85:in `new'
           +cucumber | /usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaner.rb:85:in `create_strategy'
           +cucumber | /usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaner.rb:45:in `strategy='
           +cucumber | /usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:17:in `block in strategy='
           +cucumber | /usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:17:in `each'
           +cucumber | /usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:17:in `strategy='
           +cucumber | /usr/local/lib/ruby/3.0.0/forwardable.rb:233:in `strategy='
           +cucumber | /application/features/support/database_cleaner.rb:7:in `<main>'
```

**Comment by zedtux** [comment]
Should be related to https://github.com/DatabaseCleaner/database_cleaner/issues/677

**Comment by zedtux** [comment]
With Ruby 2.7, the following warnings are appearing:

```
/usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaner.rb:85: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/database_cleaner-nobrainer-1.0.0/lib/database_cleaner/nobrainer/deletion.rb:8: warning: The called method `initialize' is defined here
```
